###########################################
# UTILIZZARE %user PER IL NOME DEL PLAYER #
# PER COLORARE LE SCRITTE USARE &         #
###########################################

settings:
  messaggioEntrata: '&a%user è entrato nel server!'
  messaggioUscita: '&4%user è uscito dal server!'
  motd:
    - '&aQuesto è un bellissimo server!'
    - '&4&bSARRA MERDA'
    - '&cCiaoooaoao'