name: DidacticPlugin
version: 1.0
main: MyPlugin
description: A Plugin for didactic only
author: Nico, Ste
commands:
      MyCommand:
        description: Comando eseguibile con alias ["m","mycomm","gervasi"]
        aliases: [m, myplug, gervasi]
      Soldi:
        description: Comando eseguibile con alia ["s", "money"]. Visualizzi i tuoi soldi
        aliases: [s, money]